package cz.machovec.lekovyportal.domain.entity

enum class DatasetType {
    ERECEPT_PRESCRIPTIONS,
    ERECEPT_DISPENSES,
    DISTRIBUTIONS_FROM_MAHS,
    DISTRIBUTIONS_FROM_DISTRIBUTORS,
    DISTRIBUTIONS_EXPORT_FROM_DISTRIBUTORS,
    DISTRIBUTIONS_FROM_PHARMACIES,
    MEDICINAL_PRODUCT_DATABASE,
}
