export enum DatasetType {
    ERECEPT_PRESCRIPTIONS = "ERECEPT_PRESCRIPTIONS",
    ERECEPT_DISPENSES = "ERECEPT_DISPENSES",
    DISTRIBUTIONS_FROM_MAHS = "DISTRIBUTIONS_FROM_MAHS",
    DISTRIBUTIONS_FROM_DISTRIBUTORS = "DISTRIBUTIONS_FROM_DISTRIBUTORS",
    DISTRIBUTIONS_FROM_PHARMACIES = "DISTRIBUTIONS_FROM_PHARMACIES"
}