CREATE TABLE IF NOT EXISTS mpd_registration_process (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_registration_status (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_dispense_type (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_addiction_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_source (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_composition_flag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    meaning     TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_government_regulation_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);
