CREATE TABLE IF NOT EXISTS mpd_registration_process (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_registration_status (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_dispense_type (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);
