CREATE TABLE IF NOT EXISTS mpd_organisation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT NOT NULL,
    country_id      BIGINT NOT NULL REFERENCES mpd_country(id) ON DELETE RESTRICT,
    name            TEXT NOT NULL,
    is_manufacturer BOOLEAN NOT NULL,
    is_marketing_authorization_holder BOOLEAN NOT NULL,
    valid_from      DATE NOT NULL,
    valid_to        DATE,
    CONSTRAINT mpd_organisation_code_country_uq UNIQUE (code, country_id)
);

CREATE TABLE IF NOT EXISTS mpd_active_substance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT UNIQUE NOT NULL,
    name_inn        TEXT NOT NULL,
    name_en         TEXT NOT NULL,
    name            TEXT NOT NULL,
    addiction_category_id BIGINT REFERENCES mpd_addiction_category(id) ON DELETE RESTRICT,
    valid_from      DATE NOT NULL,
    valid_to        DATE
);
