CREATE TABLE IF NOT EXISTS mpd_substance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT UNIQUE NOT NULL,
    source_id       BIGINT NOT NULL REFERENCES mpd_source(id) ON DELETE RESTRICT,
    name_inn        TEXT NOT NULL,
    name_en         TEXT NOT NULL,
    name            TEXT NOT NULL,
    addiction_category_id BIGINT REFERENCES mpd_addiction_category(id) ON DELETE SET NULL,
    doping_category_id BIGINT REFERENCES mpd_doping_category(id) ON DELETE SET NULL,
    government_regulation_category_id BIGINT REFERENCES mpd_government_regulation_category(id) ON DELETE SET NULL,
    valid_from      DATE NOT NULL,
    valid_to        DATE
);

CREATE TABLE IF NOT EXISTS mpd_substance_synonym (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    substance_id    BIGINT NOT NULL REFERENCES mpd_substance(id) ON DELETE CASCADE,
    sequence_number INT NOT NULL,
    source_id       BIGINT NOT NULL REFERENCES mpd_source(id) ON DELETE RESTRICT,
    name            TEXT NOT NULL,
    valid_from      DATE NOT NULL,
    valid_to        DATE
);
