CREATE TABLE IF NOT EXISTS mpd_medicinal_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sukl_code TEXT NOT NULL UNIQUE, -- Kód LP přidělený SÚKL
    name TEXT NOT NULL, -- Název LP
    registered_name TEXT, -- Registrovaný název LP
    strength TEXT, -- Síla LP
    packaging TEXT, -- Velikost balení
    supplement TEXT, -- Doplněk názvu
    ean TEXT, -- EAN kód
    expiry TEXT, -- Expirace
    expiry_type TEXT, -- Typ expirace

    atc_id BIGINT NOT NULL REFERENCES mpd_atc_group(id) ON DELETE RESTRICT, -- FK na ATC skupinu
    administration_route_id BIGINT NOT NULL REFERENCES mpd_administration_route(id) ON DELETE RESTRICT, -- FK na cestu podání
    dosage_form_id BIGINT NOT NULL REFERENCES mpd_dosage_form(id) ON DELETE RESTRICT, -- FK na lékovou formu
    package_type_id BIGINT NOT NULL REFERENCES mpd_package_type(id) ON DELETE RESTRICT, -- FK na typ obalu
    marketing_authorization_holder_id BIGINT NOT NULL REFERENCES mpd_organisation(id) ON DELETE RESTRICT, -- FK na držitele rozhodnutí o registraci
    country_id BIGINT NOT NULL REFERENCES mpd_country(id) ON DELETE RESTRICT, -- FK na zemi držitele
    registration_status_id BIGINT NOT NULL REFERENCES mpd_registration_status(id) ON DELETE RESTRICT, -- FK na stav registrace
    registration_process_id BIGINT NOT NULL REFERENCES mpd_registration_process(id) ON DELETE RESTRICT, -- FK na registrační proces
    dispense_type_id BIGINT NOT NULL REFERENCES mpd_dispense_type(id) ON DELETE RESTRICT, -- FK na typ výdeje
    addiction_category_id BIGINT REFERENCES mpd_addiction_category(id) ON DELETE SET NULL, -- FK na kategorii závislosti
    doping_category_id BIGINT REFERENCES mpd_doping_category(id) ON DELETE SET NULL, -- FK na doping
    government_regulation_category_id BIGINT REFERENCES mpd_government_regulation_category(id) ON DELETE SET NULL, -- FK na nařízení vlády

    reporting_obligation BOOLEAN NOT NULL, -- H - Označení LP pro povinné hlášení (převod z VARCHAR(1) na BOOLEAN)
    registration_number TEXT, -- RC - Registrační číslo
    parallel_import_id TEXT, -- SDOV - Identifikační číslo souběžného dovozu
    parallel_import_supplier TEXT, -- SDOV_DOD - Zkratka dovozce u souběžného dovozu
    parallel_import_country_id BIGINT REFERENCES mpd_country(id) ON DELETE SET NULL, -- SDOV_ZEM - Země dovozce u souběžného dovozu
    ddd_amount NUMERIC(6,3), -- DDDAMNT_WHO - Množství léčivé látky v DDD
    ddd_unit TEXT, -- DDDUN_WHO - Jednotka množství léčivé látky v DDD
    ddd_packaging NUMERIC(11,4), -- DDDP_WHO - Počet DDD v balení
    who_source TEXT, -- ZDROJ_WHO - WHO Index
    substance_list TEXT, -- LL - Seznam léčivých látek (oddělený čárkami)
    deliveries_flag BOOLEAN, -- DODAVKY - Označení, zda byl přípravek dodáván do lékáren
    braille_marking TEXT, -- BRAILLOVO_PISMO - Braillovo písmo (S - schváleno, V - výjimka, prázdné - nežádáno)
    mrp_number TEXT, -- MRP_CISLO - MRP číslo
    legal_basis TEXT, -- PRAVNI_ZAKLAD_REGISTRACE - Právní základ registrace
    safety_feature BOOLEAN, -- OCHRANNY_PRVEK - Ochranný prvek (A - musí mít ochranný prvek)
    prescription_restriction BOOLEAN, -- OMEZENI_PRESKRIPCE_SMP - Omezení používání dle SmPC (A - omezení)
    medicinal_product_type TEXT, -- TYP_LP - Typ léčivého přípravku

    valid_from DATE NOT NULL,
    valid_to DATE
);
