CREATE TABLE IF NOT EXISTS mpd_registration_exception (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicinal_product_id BIGINT NOT NULL REFERENCES mpd_medicinal_product(id) ON DELETE CASCADE,
    valid_from      DATE NOT NULL,
    valid_to        DATE,
    allowed_package_count INTEGER,
    purpose         TEXT,
    workplace       TEXT,
    distributor     TEXT,
    note            TEXT,
    submitter       TEXT,
    manufacturer    TEXT
);
