CREATE TABLE IF NOT EXISTS mpd_registration_exception (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicinal_product_id BIGINT NOT NULL REFERENCES mpd_medicinal_product(id) ON DELETE CASCADE,
    valid_from      DATE NOT NULL,
    valid_to        DATE,
    allowed_package_count INTEGER,
    purpose         TEXT,
    workplace       TEXT,
    distributor     TEXT,
    note            TEXT,
    submitter       TEXT,
    manufacturer    TEXT
);

CREATE TABLE IF NOT EXISTS mpd_cancelled_registration (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    administration_route_id BIGINT REFERENCES mpd_administration_route(id),
    dosage_form_id  BIGINT REFERENCES mpd_dosage_form(id),
    strength        TEXT,
    registration_number TEXT,
    parallel_import_id TEXT,
    mrp_number      TEXT,
    registration_process_id BIGINT REFERENCES mpd_registration_process(id),
    registration_legal_basis TEXT,
    marketing_authorization_holder_id BIGINT REFERENCES mpd_organisation(id),
    registration_end_date DATE,
    registration_status_id BIGINT REFERENCES mpd_registration_status(id),
    valid_from      DATE NOT NULL,
    valid_to        DATE
);
