CREATE TABLE IF NOT EXISTS erecept_prescription (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    district_code   VARCHAR(10) NOT NULL,
    year            INT NOT NULL,
    month           INT NOT NULL,
    sukl_code       VARCHAR(20) NOT NULL,
    quantity        INT NOT NULL
);

CREATE TABLE IF NOT EXISTS erecept_dispense (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    district_code   VARCHAR(10) NOT NULL,
    year            INT NOT NULL,
    month           INT NOT NULL,
    sukl_code       VARCHAR(20) NOT NULL,
    quantity        INT NOT NULL
);
