CREATE TABLE IF NOT EXISTS dist_from_mahs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year                 INT NOT NULL,
    month                INT NOT NULL,
    medicinal_product_id BIGINT NOT NULL REFERENCES mpd_medicinal_product(id),
    purchaser_type       VARCHAR(30) NOT NULL CHECK (
                            purchaser_type IN ('DISTRIBUTOR', 'AUTHORIZED_PERSON')
    ),
    movement_type        VARCHAR(20) NOT NULL CHECK (
                            movement_type IN ('DELIVERY', 'RETURN')
    ),
    package_count        NUMERIC(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS dist_from_distributors (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year                 INT NOT NULL,
    month                INT NOT NULL,
    medicinal_product_id BIGINT NOT NULL REFERENCES mpd_medicinal_product(id),
    purchaser_type       VARCHAR(50) NOT NULL CHECK (
                            purchaser_type IN (
                                'DISTRIBUTOR_CR',
                                'DISTRIBUTOR_EU',
                                'DISTRIBUTOR_NON_EU',
                                'DOCTOR',
                                'PHARMACY',
                                'NUCLEAR_MEDICINE',
                                'SALES_REPRESENTATIVE',
                                'HEALTHCARE_PROVIDER',
                                'VLP_SELLER',
                                'TRANSFUSION_SERVICE',
                                'VETERINARY_DOCTOR',
                                'FOREIGN_ENTITY'
                            )
    ),
    movement_type        VARCHAR(20) NOT NULL CHECK (
                            movement_type IN ('DELIVERY', 'RETURN')
    ),
    package_count        NUMERIC(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS dist_export_from_distributors (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year                 INT NOT NULL,
    month                INT NOT NULL,
    medicinal_product_id BIGINT NOT NULL REFERENCES mpd_medicinal_product(id),
    purchaser_type       VARCHAR(50) NOT NULL CHECK (
                            purchaser_type IN (
                                'DISTRIBUTOR_EU',
                                'DISTRIBUTOR_NON_EU',
                                'AUTHORIZED_PERSON'
                            )
    ),
    movement_type        VARCHAR(20) NOT NULL CHECK (
                            movement_type IN ('DELIVERY', 'RETURN')
    ),
    package_count        NUMERIC(10,3) NOT NULL,
    subject              VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS dist_from_pharmacies (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year                 INT NOT NULL,
    month                INT NOT NULL,
    medicinal_product_id BIGINT NOT NULL REFERENCES mpd_medicinal_product(id),
    dispense_type        VARCHAR(30) NOT NULL CHECK (
                            dispense_type IN ('PRESCRIPTION', 'REQUISITION', 'OTC')
    ),
    package_count        NUMERIC(10,3) NOT NULL
);
