CREATE TABLE IF NOT EXISTS reg_distribution (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year            INT NOT NULL,
    month           INT NOT NULL,
    sukl_code       VARCHAR(20) NOT NULL,
    purchaser_type  VARCHAR(20) NOT NULL CHECK (
                      purchaser_type IN ('DISTRIBUTOR', 'OOV')
    ),
    movement_type   VARCHAR(20) NOT NULL CHECK (
                      movement_type IN ('DELIVERY', 'RETURN')
    ),
    package_count   INT NOT NULL
);

CREATE TABLE IF NOT EXISTS dis_distribution (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year            INT NOT NULL,
    month           INT NOT NULL,
    sukl_code       VARCHAR(20) NOT NULL,
    purchaser_type  VARCHAR(50) NOT NULL CHECK (
                      purchaser_type IN (
                          'DISTRIBUTOR_CR', 'DISTRIBUTOR_EU', 'DISTRIBUTOR_MIMO_EU', 'LEKAR',
                          'LEKARNA', 'NUKLEARNI_MEDICINA', 'OBCHODNI_ZASTUPCE',
                          'OSOBA_POSKYTUJICI_ZDRAVOTNI_PECI', 'PRODEJCE_VLP', 'TRANSFUZNI_SLUZBA',
                          'VETERINARNI_LEKAR', 'ZAHRANICI'
                      )
    ),
    movement_type   VARCHAR(20) NOT NULL CHECK (
                      movement_type IN ('DELIVERY', 'RETURN')
    ),
    package_count   INT NOT NULL
);
