CREATE TABLE IF NOT EXISTS dis_abroad_distribution (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year            INT NOT NULL,
    month           INT NOT NULL,
    sukl_code       VARCHAR(20) NOT NULL,
    purchaser_type  VARCHAR(50) NOT NULL CHECK (
                      purchaser_type IN (
                          'DISTRIBUTOR_EU', 'DISTRIBUTOR_MIMO_EU', 'OOV'
                      )
    ),
    movement_type   VARCHAR(20) NOT NULL CHECK (
                      movement_type IN ('DELIVERY', 'RETURN')
    ),
    package_count   INT NOT NULL,
    subject         VARCHAR(50) NOT NULL
);