CREATE TABLE IF NOT EXISTS lek_distribution (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year            INT NOT NULL,
    month           INT NOT NULL,
    sukl_code       VARCHAR(20) NOT NULL,
    dispense_type   VARCHAR(50) NOT NULL CHECK (
                      dispense_type IN (
                          'PRESCRIPTION', 'REQUISITION', 'OTC'
                      )
    ),
    package_count   NUMERIC(10,3) NOT NULL
);