ALTER TABLE processed_dataset DROP CONSTRAINT processed_dataset_dataset_type_check;

ALTER TABLE processed_dataset ADD CONSTRAINT processed_dataset_dataset_type_check
CHECK (dataset_type IN
    ('ERECEPT_PREDPIS', 'ERECEPT_VYDEJ',
     'DISTRIBUCE_REG', 'DISTRIBUCE_DIS',
     'DISTRIBUCE_DIS_ZAHRANICI', 'DISTRIBUCE_LEK', 'MPD')
);

CREATE TABLE IF NOT EXISTS mpd_indication_group (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);
