CREATE TABLE IF NOT EXISTS mpd_country (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(3) UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    name_en     TEXT NOT NULL,
    edqm_code   VARCHAR(2),
    valid_from  DATE NOT NULL,
    valid_to    DATE
);
