CREATE TABLE IF NOT EXISTS mpd_measurement_unit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);
