CREATE TABLE IF NOT EXISTS mpd_country (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(3) UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    name_en     TEXT NOT NULL,
    edqm_code   VARCHAR(2),
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_package_type (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    name_en     TEXT NOT NULL,
    edqm_code   BIGINT,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_administration_route (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    name_en     TEXT NOT NULL,
    name_lat    TEXT NOT NULL,
    edqm_code   BIGINT,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);

CREATE TABLE IF NOT EXISTS mpd_dosage_form (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    name_en     TEXT NOT NULL,
    name_lat    TEXT NOT NULL,
    is_cannabis BOOLEAN NOT NULL,
    edqm_code   BIGINT,
    valid_from  DATE NOT NULL,
    valid_to    DATE
);
